version: '3.9'

services:
    java-api:
        container_name: crm-api
        image: gradle:latest # this is due to some Mac M1 issues with Docker :_
        depends_on:
            -   postgres-db
        volumes:
            -   "/C/Users/manu6/IdeaProjects/crm:/home/gradle/project"
            -   "gradle-cache:/home/gradle/.gradle"
        working_dir: "/home/gradle/project"
        ports:
            -   "8080:8080"
        networks:
            internal-net:

    postgres-db:
        container_name: postgres-db
        image: postgres:13.4-alpine
        restart: on-failure
        volumes:
            - volume:/var/lib/postgresql/data
        env_file:
            - postgres.dev.env
        ports:
            - "5432:5432"
        networks:
            internal-net:

volumes:
    volume:
    gradle-cache:

networks:
    internal-net:
        name: net
